### ISSUE TITLE
Losing :focus when using links inside tabs

### ISSUE THREAD

**Issue by nicholasio** [10up/component-library#18]
**Describe the bug**
If tabpanel(s) include links, :focus disappears or goes to inactive tab and is not trapped inside of the active tab when browsing with tab key.

**To Reproduce**
1. Add links to tabs of the demo index.html
```
<div class="tab-content" id="js-tab1" role="tabpanel">
  <h2>Tab 1 Content</h2>
  <p><a href="#1">Link-1</a> ipsum dolor sit amet, consectetur adipiscing elit.</p>
</div><!-- //.tab-content -->

<div class="tab-content" id="js-tab2" role="tabpanel">
  <h2>Tab 2 Content</h2>
  <p><a href="#2">Link-2</a> tincidunt tempor risus gravida tincidunt.</p>
</div><!-- //.tab-content -->
```
2. Open in browser
3. Browse with tab key
4. After focusing "Link-1" press tab again
5. Focus now goes to "Link-2" but it's not clear to user that tab has changed.

**Expected behavior**
User could tab-browse all links inside of a tab, and then focus moves to next .tab-item (where you change tab).

**Desktop (please complete the following information):**
 - OS: [Mac OS Catalina]
 - Browser [Atleast all webkit browsers]

**Mobile (please complete the following information):**
- Not an issue on mobile device, atleast when using touchscreen

**Comment by Firestorm980** [comment]
@nicholasio @jeffpaul I had an old PR here so I can take this one on, its a pretty simple CSS change.

**Comment by nicholasio** [comment]
> @nicholasio @jeffpaul I had an old PR here so I can take this one on, its a pretty simple CSS change.

Thanks!

**Comment by Firestorm980** [comment]
@jeffpaul @nicholasio PR opened above, ready for a review.

**Comment by nicholasio** [comment]
The fix has been merged. Thanks for the contribution @Firestorm980
