### ISSUE TITLE
Nested Tabs Block Won't Switch Tabs

### ISSUE THREAD

**Issue by tlovett1** [10up/component-library#93]
If you have a tabs component inside another tabs component you aren't able to interact with the tabs of the inner component: https://www.screencast.com/t/jqzcKFaZ

**Comment by xavortm** [comment]
It took me a lot of time to find what was going on, JS isn't my strength, but I think the solution was quite simple — `getTabLinksAndList` was returning incorrect information when tabs were nested. I also did a minor update to run the `setupTabs` only once for every tabs element vs for every tab item. (for the demo, that would be 3 times to be run vs 20)

![Screenshot 2021-12-22 at 14 58 50](https://user-images.githubusercontent.com/2004664/147096618-0ca7679f-5575-4569-a52c-1c86e5822f6c.gif)
